
title: Jekyll SEO Tag
description: A Jekyll plugin to add metadata tags for search engines and social networks to better index and display your site's content.

permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
image: path: https://htmlpasta.com/content/images/size/w2000/2020/06/low-angle-photo-of-fireworks-949592.jpg
author:
  twitter: benbalter
theme: jekyll-theme-minimal
